name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.3
        with:
          version: master

      - name: Install Jemalloc
        run: sudo apt install -y libjemalloc-dev

      - name: Build
        run: zig build --verbose

      - name: Run tests
        run: zig build test --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.3
        with:
          version: master

      - name: Check formatting
        run: zig fmt --check build.zig src/
